### ISSUE TITLE
New release broken

### ISSUE THREAD

**Issue by imnewo** [kermeow/coopdx-bubble-chat#1]
The new release is broken because the zip file was uploaded wrong, there should be the extra folder in the zip file

<details><summary>Detailed</summary>

<p>Here's the visualisation i made in cmd (if i didn't explain it well enough)</p>
<image src="https://i.imgur.com/URhiOIT.png"></image>
<p><i>bottom is correct</i></p>
</details>

**Comment by kermeow** [comment]
There is no requirement for zip files to be structured this way.
Importing the zip by manual extraction works fine, provided you make the folder for it.
Maybe in a future release I will fix it for importing through the game, but for now this is not a big issue.
